const isProd = process.env.NODE_ENV === 'production';

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  trailingSlash: true,
  skipTrailingSlashRedirect: true,
  distDir: 'out',
  basePath: isProd ? '/your-repo-name' : '',
  assetPrefix: isProd ? '/your-repo-name/' : '',
  images: {
    unoptimized: true, // Required for static export
  },
  // Enable static generation for dynamic routes
  exportPathMap: async function (defaultPathMap, { dev, dir, outDir, distDir, buildId }) {
    const paths = {};
    
    // Add your custom paths here
    paths['/'] = { page: '/' };
    paths['/cart'] = { page: '/cart' };
    
    // Dynamic product pages will be generated by getStaticPaths
    
    return paths;
  },
}

module.exports = nextConfig;